// Generated by Wrangler on Sat Jun 29 2024 08:35:12 GMT+0100 (Central European Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  FACEBOOK_PIXEL_ID: any;
  FACEBOOK_ACCESS_TOKEN: any;
  UPLOADTHING_SECRET: any;
  RESEND_API_KEY: any;
  LOGTO_SIGNING_KEY: any;
  API_ENDPOINT: any;
  BASE_URL: any;
	DB: D1Database;
}
